name: Docker

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - "epyc7002-7.1"
        include:
        - module: epyc7002-7.1
          platforms: epyc7002
          toolkit_ver: 7.1
    timeout-minutes: 60
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Prepare GitHub Container Registry Repository Name
      run: |
        IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        echo IMAGE_REPOSITORY=$IMAGE_REPOSITORY >> $GITHUB_ENV
        echo image repository: $IMAGE_REPOSITORY

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        build-args: |-
          PLATFORM=${{ matrix.platforms }}
          TOOLKIT_VER=${{ matrix.toolkit_ver }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/syno-toolkit:${{ matrix.platforms }}-${{ matrix.toolkit_ver }}
          ghcr.io/${{ github.repository }}:${{ matrix.platforms }}-${{ matrix.toolkit_ver }}
        push: true
